[package]

name = "uo-rust-libs"
version = "0.0.1"
edition = "2024"
authors = ["Tony Aldridge <tony@angry-lawyer.com>"]

[lib]

name = "uorustlibs"
path = "src/lib.rs"

[dependencies]
byteorder = "1.5"
image = "0.23"
